# Generated by Django 5.1 on 2024-09-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0002_alter_album_musician_alter_album_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
