# Generated by Django 5.1 on 2024-09-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategory',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='task_categories', to='task.taskmodel'),
        ),
    ]
